aamp/UI/urls.py
from django.conf.urls import include, url
from UI import views
from .views import index, info, poi_list

urlpatterns = [
	url(r'^logo/$', views.index, name="index"),
	url(r'^info/$', info, name="info"),
	url(r'^map/$', views.poi_list, name="map"),
]

aamp/aamp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from useraccount.views import index

from aamp.sitemaps import ProductSitemap, CategorySitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views

from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import (
				AddressSelectFormView, 
				UserAddressCreateView,
				UserShippingAddressCreateView, 
				OrderList, 
				OrderDetail,
				InvoicePDFView,
				UserAddressUpdateView,
				cancel_order,
				admin_orders,
				admin_cancel_order,
				feedback,
                get_feedback,
				)

sitemaps = {
			  'products' : ProductSitemap,
			  'categories': CategorySitemap,
			  'staticPages': StaticViewSitemap
			}

urlpatterns = [
	url(r'^$', index, name="home"),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('useraccount.urls', namespace="account")),
	url(r'^products/', include('products.urls', namespace="products")),
	url(r'^ui/', include('UI.urls', namespace="ui")),

	url('', include('django.contrib.auth.urls', namespace='auth')),

	url(r'^orders/$', OrderList.as_view(), name="orders"),
	url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name="order_detail"),
	url(r'^user-feedback/$', feedback, name="feedback"),
    url(r'^feedback-sent/$', get_feedback, name="feedback_send"),
	url(r'^cancel/(?P<pk>\d+)/$', cancel_order, name="cancel_order"),
	url(r'^adminorders/(?P<pk>\d+)/$', admin_orders, name="admin_orders"),
	url(r'^admincancel/(?P<pk>\d+)/$', admin_cancel_order, name="admin_cancel_order"),

	url(r'^cart/$', CartView.as_view(), name="cart"),
	url(r'^cart/count/$', ItemCountView.as_view(), name="item_count"),
	url(r'^checkout/$', CheckoutView.as_view(), name="checkout"),
	url(r'^checkout/address/$', AddressSelectFormView.as_view(), name="order_address"),
	url(r'^checkout/address/add/$', UserAddressCreateView.as_view(), name="user_address_create"),
	url(r'^checkout/address/change/(?P<pk>\d+)/$', UserAddressUpdateView.as_view(), name="user_address_update"),
	url(r'^checkout/shipping_address/add/$', UserShippingAddressCreateView.as_view(), name="user_shipping_address_create"),
	url(r'^checkout/final/$', CheckoutFinalView.as_view(), name="checkout_final"),
	
	url(r'^invoice/(?P<pk>\d+)/$', InvoicePDFView.as_view(), name='invoice'),

	url(r'^payu/', include('payu.urls', namespace='payu')),

	url(r'^social_accounts/', include('allauth.urls')),

	url(r'^care/', include('care.urls', namespace="care")),

	### SiteMap Indexing ########
	url(r'^sitemap.xml/$', views.index, {'sitemaps': sitemaps}),
	url(r'^sitemap-(?P<section>.+).xml/$', views.sitemap, {'sitemaps': sitemaps}),
	url(r'^robots.txt/', include('robots.urls')),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Shoffex Online Retails India Pvt Ltd'

aamp/products/urls.py
from django.conf.urls import include, url

from .views import ProductDetailView, ProductListView, ProductColorView, category_list, product_rating, availability, Wishlist, add_wishlist

urlpatterns = [

	url(r'^availability/$', availability, name='availability'),
	url(r'^$', ProductListView.as_view(), name="product_list"),
	url(r'^wishlist/$', Wishlist.as_view(), name="wishlist"),
	url(r'^wishlist/(?P<pk>\d+)/$', add_wishlist, name="add_wishlist"),
	url(r'^rating/(?P<pk>\d+)/$', product_rating, name="rating"),
	url(r'^color_view/$', ProductColorView.as_view(), name="color_view"),
    url(r'^(?P<slug>[-\w]+)/$', ProductDetailView.as_view(), name="product_detail"),
    url(r'^category/(?P<slug>[-\w]+)/$', category_list, name="single_category_products"),
]

aamp/useraccount/urls.py
from django.conf.urls import url


from .views import (
		signup, 
		signup_mobile, 
		login_user, 
		user_account, 
		user_settings,
		forget_pass,
		pass_reset,
		replace_pass,
		order_tracking

		)

urlpatterns = [
    url(r'^signup/$', signup, name="signup" ),
    url(r'^order-tracking/$', order_tracking, name="order_tracking" ),
    url(r'^login/$', login_user, name="login_user" ),
    url(r'^mobile/$', signup_mobile, name="signup_mobile" ),
    url(r'^personal/$', user_account, name="user_account" ),
    url(r'^user-settings/$', user_settings, name="user_settings" ),

    url(r'^password/', forget_pass, name="forget_pass"),
    url(r'^reset/', pass_reset, name="password_reset"),
    url(r'^replace/', replace_pass, name="replace_pass"),


]

aamp/templates/alert.html
<div class='container container-alert-flash'><div class='col-sm-3 col-sm-offset-8'><div class='alert alert-success alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>{{ message }}</div></div></div>

aamp/templates/category_menu.html
{% load mptt_tags %}
{% load logo_tags %}
{% load staticfiles %}
<style type="text/css">


.description {
    position: absolute;
    top: 50%;
    left: 50%;
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
    -webkit-transform: translateX(-50%);
    -ms-transform: translateX(-50%);
    transform: translateX(-50%);
}



.menu-container {
    width: 100%;
    margin: 0 auto;
    background: rgb(0, 108, 180);
}

.menu-mobile {
    display: none;
    padding: 20px;
}

.menu-mobile:after {
    content: "\f00b";
    font-family: FontAwesome;
    font-size: 2.5rem;
    padding: 0;
    float: right;
    position: relative;
    top: 50%;
    -webkit-transform: translateY(-25%);
    -ms-transform: translateY(-25%);
    transform: translateY(-25%);
}

.menu-dropdown-icon:before {
    content: "\f13a";
    font-family: FontAwesome;
    display: none;
    cursor: pointer;
    float: right;
    padding: 1.5em 2em;
    background: #fff;
    color: #333;
}

.menu > ul {
    margin: 0 auto;
    width: 100%;
    list-style: none;
    padding: 0;
    position: relative;
   
    box-sizing: border-box;

}

.menu > ul:before,
.menu > ul:after {
    content: "";
    display: table;
}

.menu > ul:after {
    clear: both;
}

.menu > ul > li {
    float: left;
    background: rgb(0, 108, 180);
    padding: 0;
    margin: 0;

}

.menu > ul > li a {
    text-decoration: none;
    padding: 0.5em 1.5em;
    display: block;
    color:white;
}

.menu > ul > li:hover a {
    color:black;
}

.menu > ul > li:hover {
    background: #f0f0f0;
    border-top-left-radius:5px;
    border-top-right-radius:5px;
}

.menu > ul > li > ul {
    display: none;
    width: 100%;
    background: #f0f0f0;
    padding: 20px;
    position: absolute;
    z-index: 99;
    left: 0;
    margin: 0;
    list-style: none;
    box-sizing: border-box;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
}

.menu > ul > li > ul:before,
.menu > ul > li > ul:after {
    content: "";
    display: table;
}

.menu > ul > li > ul:after {
    clear: both;
}

.menu > ul > li > ul > li {
    margin: 0;
    padding-bottom: 0;
    list-style: none;
    width: 25%;
    background: none;
    float: left;
}

.menu > ul > li > ul > li a {
    color: #777;
    padding: .2em 0;
    width: 95%;
    display: block;
    border-bottom: 1px solid #ccc;
}
.menu > ul > li > ul > li a:hover {
    border: 1px solid orange;
}

.menu > ul > li > ul > li > ul {
    display: block;
    padding: 0;
    margin: 10px 0 0;
    list-style: none;
    box-sizing: border-box;
}

.menu > ul > li > ul > li > ul:before,
.menu > ul > li > ul > li > ul:after {
    content: "";
    display: table;
}

.menu > ul > li > ul > li > ul:after {
    clear: both;
}

.menu > ul > li > ul > li > ul > li {
    float: left;
    width: 100%;
    padding: 10px 0;
    margin: 0;
    font-size: .8em;
}

.menu > ul > li > ul > li > ul > li a {
    border: 0;
}

.menu > ul > li > ul.normal-sub {
    width: 300px;
    left: auto;
    padding: 10px 20px;
}

.menu > ul > li > ul.normal-sub > li {
    width: 100%;
}

.menu > ul > li > ul.normal-sub > li a {
    border: 0;
    padding: 1em 0;
}


/* ––––––––––––––––––––––––––––––––––––––––––––––––––
Mobile style's
–––––––––––––––––––––––––––––––––––––––––––––––––– */

@media only screen and (max-width: 959px) {
    .menu-container {
        width: 100%;
    }
    .menu-mobile {
        display: block;
    }
    .menu-dropdown-icon:before {
        display: block;
    }
    .menu > ul {
        display: none;
    }
    .menu > ul > li {
        width: 100%;
        float: none;
        display: block;
    }
    .menu > ul > li a {
        padding: 1.5em;
        width: 100%;
        display: block;
    }
    .menu > ul > li > ul {
        position: relative;
    }
    .menu > ul > li > ul.normal-sub {
        width: 100%;
    }
    .menu > ul > li > ul > li {
        float: none;
        width: 100%;
        margin-top: 20px;
    }
    .menu > ul > li > ul > li:first-child {
        margin: 0;
    }
    .menu > ul > li > ul > li > ul {
        position: relative;
    }
    .menu > ul > li > ul > li > ul > li {
        float: none;
    }
    .menu .show-on-mobile {
        display: block;
    }
}
</style>


{% set_node as nodes %}
<div class="container">
<div class="menu-container">
        <div class="menu">
            <ul>
				{% recursetree nodes %}
			   <li><a href="{% url 'products:single_category_products' node.slug %}">{{ node.name }}</a>
			   		{% if not node.is_leaf_node %}
			   		<ul>
			        	{{ children }}
				    </ul>
				    {% endif %}
			   </li>

			    {% endrecursetree %}
			</ul>
        </div>
    </div>
 </div>

aamp/templates/demo.html
{% load mptt_tags %}
<ul>
    {% recursetree nodes %}
        <li>
            {{ node.name }}
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

aamp/templates/footer.html
{% load mptt_tags %}
{% load logo_tags %}
{% load staticfiles %}
<style type="text/css">
	.footer-distributed{
	background-color: #292c2f;
	box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
	box-sizing: border-box;
	width: 100%;
	text-align: left;
	font: bold 16px sans-serif;

	padding: 55px 50px;
	margin-top: 80px;
}

.footer-distributed .footer-left,
.footer-distributed .footer-center,
.footer-distributed .footer-right{
	display: inline-block;
	vertical-align: top;
}

/* Footer left */

.footer-distributed .footer-left{
	width: 40%;
}

/* The company logo */

.footer-distributed h3{
	color:  #ffffff;
	font: normal 36px 'Cookie', cursive;
	margin: 0;
}

.footer-distributed h3 span{
	color:  #5383d3;
}

/* Footer links */

.footer-distributed .footer-links{
	color:  #ffffff;
	margin: 20px 0 12px;
	padding: 0;
}

.footer-distributed .footer-links a{
	/*display:inline-block;*/
	line-height: 1.8;
	text-decoration: none;
	color:  inherit;
	list-style: none;
	font-size: small;
	font-family: initial;
}
.footer-distributed .footer-links hr{ 
	margin-top: 0px; 
	margin-bottom: 0px;
	border-color: #696365;
}
.footer-distributed .footer-company-name{
	color:  #8f9296;
	font-size: 14px;
	font-weight: normal;
	margin: 0;
}

/* Footer Center */

.footer-distributed .footer-center{
	width: 35%;
}

.footer-distributed .footer-center i{
	background-color:  #33383b;
	color: #ffffff;
	font-size: 25px;
	width: 38px;
	height: 38px;
	border-radius: 50%;
	text-align: center;
	line-height: 42px;
	margin: 10px 15px;
	vertical-align: middle;
}


.footer-distributed .footer-center i.fa-envelope{
	font-size: 17px;
	line-height: 38px;
}

.footer-distributed .footer-center p{
	display: inline-block;
	color: #ffffff;
	vertical-align: middle;
	margin:0;
}

.footer-distributed .footer-center p span{
	display:block;
	font-weight: normal;
	font-size:14px;
	line-height:2;
}

.footer-distributed .footer-center p a{
	color:  #5383d3;
	text-decoration: none;;
}


/* Footer Right */

.footer-distributed .footer-right{
	width: 20%;
}

.footer-distributed .footer-company-about{
	line-height: 20px;
	color:  #92999f;
	font-size: 13px;
	font-weight: normal;
	margin: 0;
}

.footer-distributed .footer-company-about span{
	display: block;
	color:  #ffffff;
	font-size: 14px;
	font-weight: bold;
	margin-bottom: 20px;
}

.footer-distributed .footer-icons{
	margin-top: 25px;
}

.footer-distributed .footer-icons a{
	display: inline-block;
	width: 35px;
	height: 35px;
	cursor: pointer;
	background-color:  #33383b;
	border-radius: 2px;

	font-size: 20px;
	color: #ffffff;
	text-align: center;
	line-height: 35px;

	margin-right: 3px;
	margin-bottom: 5px;
}

/* If you don't want the footer to be responsive, remove these media queries */

@media (max-width: 880px) {

	.footer-distributed{
		font: bold 14px sans-serif;
	}

	.footer-distributed .footer-left,
	.footer-distributed .footer-center,
	.footer-distributed .footer-right{
		display: block;
		width: 100%;
		margin-bottom: 40px;
		text-align: center;
	}

	.footer-distributed .footer-center i{
		margin-left: 0;
	}

}
.footer-distributed .container .row
{
	margin-top: -50px;
}
#trust
{
	margin-right: 20px; 
	margin-left: 0px;
	width : 200px ;
	height : 100px;
}
#express{
	margin-right: 10px;
}

</style>


<footer class="footer-distributed">
	<div class="container hidden-xs" >
		<div class="row">
	    	<img id="trust" src="{% static 'image/TrustPay.png' %}" >
	    	<img id="payu" src="{% static 'image/Payu.jpg' %}">
	    	<img id="paytm" src="{% static 'image/Paytm.png' %}">
	    	<img id="express" src="{% static 'image/express-1.png' %}">
	    	<img src="{% static 'image/master.png' %}">
	    </div>
	</div>

      <div class="footer-left">

      	<h3>Shoffex.com<span></span></h3>
      <div class="col-md-6 col-sm-6">
      <h4 style="color: #ffffff;">Information</h4>
      {% load ui_extras %}
			{% footer_tag as pages %}
			<ul class="footer-links" style="list-style: none; ">
			{% for i in pages %}
				{% if i.url %}
				
				{% if i.is_it_location %}
				<li><i class="fa fa-angle-double-right"></i>&nbsp;<a href="{{ i.url }}">{{ i }}&nbsp;<span><i class="fa fa-map-marker fa-1x"></i></span></a></li>
	          <hr>
	          	{% else %}
	          	<li><i class="fa fa-angle-double-right"></i>&nbsp;<a href="{{ i.url }}">{{ i }}</a></li>
	          <hr>
	          	{% endif %}
				{% else %}
				<li><i class="fa fa-angle-double-right"></i>&nbsp;<a href="{% url 'ui:info' %}?id={{i.id}}" style="color: white;text-decoration: none;">{{ i }}</a></li>
				<hr>
				{% endif %}
			{% endfor %}
			</ul>

      </div>
      
       <div class="col-md-6 col-sm-6">
       <h4 style="color: #ffffff;">Categories</h4>
       {% set_node as nodes %}
      	<ul class="footer-links" style="list-style: none; ">
      		{% recursetree nodes %}
	          <li><i class="fa fa-angle-double-right"></i>&nbsp;<a href="#">{{ node.name }}</a></li>
	          <hr>
	        {% endrecursetree %}
	        </ul>
      	
      </div>
      <div>
        	<img src="{% static 'image/trusted.png' %}">
        </div>

    </div>

      <div class="footer-center">

        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>Shoffex Online Retails India Pvt Ltd<br/>13, Second Floor,Indraneel Appartment,<br/>Near D-mart, Ashwamedh Nagar,<br/> Pune 411009, India.</span></p>
        </div>

       <!--  <div>
          <i class="fa fa-phone"></i>
          <p>+1 555 123456</p>
        </div> -->

        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="mailto:care@shoffex.com" style="font-size: small;">care@shoffex.com</a></p>
        </div>

      </div>

      <div class="footer-right">

        <p class="footer-company-about">
          <span>About the company</span>
          The ShOffex.com is Product Of Shoffex Online Retails India Pvt Ltd , which vision is to provide service in Urban and Rural areas. Our mission is to provide best of the products/brands at the lowest prices with great online shopping experience. Especially we want to provide our best services and quality products for Rural India thorough online shopping. So Without the hassles of driving to the urban area locate the shop, rural customers will get best products at economical prices.
        </p>
        <div class="footer-icons">

         <!--  <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-github"></i></a> -->

        </div>
        

      </div>
      <div>
      	<hr style="border-color: #696365;">
      	<p class="footer-company-name"> &copy; All rights reserved by shoffex.com </p>
      </div>
    </footer>

aamp/templates/head_css.html
{% load staticfiles %}

<!-- Bootstrap core CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/category_menu.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/category_menu.css' %}">


<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

aamp/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
<style>
{% block style %}
.home_products{
	padding-top: 20px;
}


.button_go {
  border-radius: 4px;
  background-color: #f4511e;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 16px;
  padding: 10px;
  width: 150px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button_go span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button_go span:after {
  content: '»';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button_go:hover span {
  padding-right: 25px;
}

.button_go:hover span:after {
  opacity: 1;
  right: 0;
}

{% endblock style %}
</style>
{% block content %}

{% if offers %}
<div class="row">
	<div class="col-lg-12">
		<h3 style="font-family: ‘Times New Roman’, Times, serif;">Best in Products</h3>
	</div>
</div>

<div class="row">
{% for offer in offers %}
	{% if offer.active %}
	<div class="col-lg-3 text-center">
		<a href="{{ offer.url }}"><img src="media/{{ offer.offer }}" style="width:270px; height: 190px;"></a>
		<a href="{{ offer.url }}"><button style="margin-top: -40px;" class="btn btn-warning">Shop Now</button></a>
		<br>
		<br>
	</div>
	{% endif %}
{% endfor %}
</div>




{% endif %}


<br>
{% if cat %}
{% for key, value in cat.items %}
{% if value %}
<div class="container-fluied" style="box-shadow: 1px 4px 6px 5px #888888;">
	<div class="row">
		<div class="col-lg-4">
			<h3 class="visible-lg visible-md" style="text-transform: uppercase;margin-left: 20px;text-align: left;">{{ key }}</h3>
			<h3 class="visible-xs" style="text-transform: uppercase;text-align: center;">{{ key }}</h3>
		</div>
		<div class="col-lg-6">
			
		</div>
		<div class="col-lg-2 text-center">
			<a href="{% url 'products:single_category_products' key.slug %}" target="_blank"><button class="btn btn-primary" style="margin-top: 10px;">View All</button></a>
			
		</div>
	</div>
	<hr style="margin-top: 0px;margin-bottom: 0px;">
	<div class="row">
		{% for product in value %}
		{% if product.active %}
		<a href="{{ product.get_absolute_url }}">
		<div class="col-lg-2 text-center">
			<img src="{{ product.get_image_url }}" style="height: 200px;max-width: 95%;max-height:100%;">
			<figcaption style="color:black;">{{ product.title }}</figcaption>
			{% if product.sale_price %}
			<h5>{{ product.sale_price }} <small style="color:red;"><del> {{ product.price }}</del></small></h5>
			{% else %}
			<h5>{{ product.price }}</h5>
			{% endif %}
		</div>
		</a>
		{% endif %}
		{% endfor %}
	</div>
</div>
<br>
{% endif %}
{% endfor %}
{% endif %}





{% if bottom %}
<div class="row">
	<div class="col-lg-12 hidden-md hidden-sm hidden-xs">
		<span style="font-family: ‘Times New Roman’, Times, serif;font-size: 22px;">New Shoffex Offers</span>
	</div>
</div>
<div class="row">
{% for offer in bottom %}
{% if offer.active %}
	<div class="col-lg-6 col-md-6 hidden-sm hidden-xs text-center">
		<a href="{{ offer.url }}"><img src="media/{{ offer.offer }}" style="width:570px; height: 180px;"></a>
		<a href="{{ offer.url }}"><button class="button_go"><span> Shop Now</span> </button></a>
	</div>
{% endif %}
{% endfor %}
</div>
<br>
{% endif %}

{% endblock content %}

aamp/templates/navbar.html
{% load staticfiles %}
<nav class="nav navbar-fixed-top" style="max-height: 50px; background-color: rgb(2, 124, 213); height: 50px;">
    <div class="container">
      <div class="row" style="padding-top: 5px;">
        <div class="col-sm-3 text-center col-xs-4">
            {% load logo_tags %}
            {% set_logo as logo %}
            {% if logo %}
              <div style="text-align: -moz-center;padding-top: 3px;">
                <a href="/"><img src="{{ logo }}" class="img-responsive" style="max-height: 38px;"></a>
              </div>
            {% else %}
              <div style="margin-top: -16px;" class="visible-lg">
                <a href="/" style="text-decoration: none;color: white;"><span><h2>SHOFFEX</h2></span></a>
              </div>
              <div class="visible-xs">
                <a href="/" style="text-decoration: none;color: white;"><span><h4>SHOFFEX</h4></span></a>
              </div>
            {% endif %}
        </div>
        <div class="col-sm-6 hidden-xs">
          <div style="padding-top: 3px;">
            <form role="search" method="GET" action='{% url "products:product_list" %}'>
                <div class="input-group"> 
                    <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.GET.q }}">
                  <span class="input-group-btn">
                  <button type="submit" class="btn btn-warning" style="color: #565656;">SEARCH</button>
                  </span>
                </div>
            </form>
          </div>
        </div>


        <div class="col-sm-3 text-center col-xs-8">
          <div class="row" style="margin-top: 3px;">

            <div class="btn-group visible-xs">
            <button type="button" style="width:50px; height: 34px;" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-search-plus" style="font-size: 24px;margin-top: -2px;"></i>
            </button>
            <ul class="dropdown-menu dropdown-mobile-search">
              <li>
                <form role="search" method="GET" action='{% url "products:product_list" %}'>
                    <div> 
                        <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.GET.q }}">
                    </div>
                </form>
              </li>
            </ul>
          </div>

            <div id="msg-cart" class="btn" style="background-color: #006cb4;width:80px; height: 34px;">
              <a class="fa-navbar-cart" href='{% url "cart" %}' style="">
                <i class="fa fa-shopping-cart fa-navbar-cart" style="color: white; font-size: 20px;margin-top: -9px;"></i> 
                <span id="cart-count-badge" class="badge" style="margin-top: -4px;">{{ request.session.cart_item_count }}</span>
              </a>
            </div>

            <!-- Single button -->
            <div class="btn-group">
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user" style="font-size: 20px;"></i><span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-account">
                {% if user and not user.is_anonymous %}
                    <li><a href="{% url 'account:user_account' %}">{{ request.user }}</a></li>
                    <li><a href="{% url 'orders' %}">Orders</a></li>
                    <li><a href="{% url 'account:order_tracking' %}">Track My Order</a></li>
                    <li><a href="{% url 'products:wishlist' %}">My Wishlist</a></li>
                    <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:login_user' %}?next={{ request.path }}">SignUp or Login</a></li>
                {% endif %}
                
                
              </ul>
            </div>
            <!--single button end-->
            <div class="btn-group hidden-xs hidden-sm">
              {% if user and not user.is_anonymous %}
                <h5 style="color: white; margin-left: 20%;">  Hi! {{ request.user }}</h5>
              {% else %}
                <h5> </h5>
              {% endif %}
            </div>
          </div>
        
        </div>

      </div>

    </div>

</nav>