aamp/UI/urls.py
from django.conf.urls import include, url
from UI import views
from .views import index, info, poi_list

urlpatterns = [
	url(r'^logo/$', views.index, name="index"),
	url(r'^info/$', info, name="info"),
	url(r'^map/$', views.poi_list, name="map"),
]

aamp/aamp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from useraccount.views import index

from aamp.sitemaps import ProductSitemap, CategorySitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views

from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import (
				AddressSelectFormView, 
				UserAddressCreateView,
				UserShippingAddressCreateView, 
				OrderList, 
				OrderDetail,
				InvoicePDFView,
				UserAddressUpdateView,
				cancel_order,
				admin_orders,
				admin_cancel_order,
				feedback,
                get_feedback,
				)

sitemaps = {
			  'products' : ProductSitemap,
			  'categories': CategorySitemap,
			  'staticPages': StaticViewSitemap
			}

urlpatterns = [
	url(r'^$', index, name="home"),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('useraccount.urls', namespace="account")),
	url(r'^products/', include('products.urls', namespace="products")),
	url(r'^ui/', include('UI.urls', namespace="ui")),

	url('', include('django.contrib.auth.urls', namespace='auth')),

	url(r'^orders/$', OrderList.as_view(), name="orders"),
	url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name="order_detail"),
	url(r'^user-feedback/$', feedback, name="feedback"),
    url(r'^feedback-sent/$', get_feedback, name="feedback_send"),
	url(r'^cancel/(?P<pk>\d+)/$', cancel_order, name="cancel_order"),
	url(r'^adminorders/(?P<pk>\d+)/$', admin_orders, name="admin_orders"),
	url(r'^admincancel/(?P<pk>\d+)/$', admin_cancel_order, name="admin_cancel_order"),

	url(r'^cart/$', CartView.as_view(), name="cart"),
	url(r'^cart/count/$', ItemCountView.as_view(), name="item_count"),
	url(r'^checkout/$', CheckoutView.as_view(), name="checkout"),
	url(r'^checkout/address/$', AddressSelectFormView.as_view(), name="order_address"),
	url(r'^checkout/address/add/$', UserAddressCreateView.as_view(), name="user_address_create"),
	url(r'^checkout/address/change/(?P<pk>\d+)/$', UserAddressUpdateView.as_view(), name="user_address_update"),
	url(r'^checkout/shipping_address/add/$', UserShippingAddressCreateView.as_view(), name="user_shipping_address_create"),
	url(r'^checkout/final/$', CheckoutFinalView.as_view(), name="checkout_final"),
	
	url(r'^invoice/(?P<pk>\d+)/$', InvoicePDFView.as_view(), name='invoice'),

	url(r'^payu/', include('payu.urls', namespace='payu')),

	url(r'^social_accounts/', include('allauth.urls')),

	url(r'^care/', include('care.urls', namespace="care")),

	### SiteMap Indexing ########
	url(r'^sitemap.xml/$', views.index, {'sitemaps': sitemaps}),
	url(r'^sitemap-(?P<section>.+).xml/$', views.sitemap, {'sitemaps': sitemaps}),
	url(r'^robots.txt/', include('robots.urls')),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Shoffex Online Retails India Pvt Ltd'

aamp/care/urls.py
from django.conf.urls import include, url
from .views import (
	care_user_login, 
	CareOrderListView, 
	CareCommission, 
	CareWallet, 
	CareFaqsListView, 
	care_contact, 
	care_my_account, 
	care_myArea, 
	CareDashboard,
	change_password,
	update_user_information,
	care_query_send,
	care_forget_pass,
	update_bank_detail_information,
	upadate_bank_docs,
	CareOrderDetailView,
	)

urlpatterns = [
	url(r'^$', care_user_login, name='care_login'),
	url(r'^faqs/$', CareFaqsListView.as_view(), name='care_faqs'),
	url(r'^forget/', care_forget_pass, name='care_forget_pass'),
	url(r'^dashboard/$', CareDashboard.as_view(), name='care_dashboard'),
	url(r'^orders/$', CareOrderListView.as_view(), name='care_orders'),
	url(r'^orders/(?P<pk>\d+)/$', CareOrderDetailView.as_view(), name='care_order_detail'),
	url(r'^commission/$', CareCommission.as_view(), name='care_commission'),
	url(r'^wallet/$', CareWallet.as_view(), name='care_wallet'),
	url(r'^contact/$', care_contact, name='care_contact'),
	url(r'^account/$', care_my_account, name='care_my_account'),
	url(r'^myarea/$', care_myArea, name='care_myArea'),
	url(r'^change_password/$', change_password, name='change_password'),
	url(r'^update_info/$', update_user_information, name='update_info'),
	url(r'^query_send/$', care_query_send, name='query_send'),
	url(r'^update_bank_info/$', update_bank_detail_information, name='update_bank_info'),
	url(r'^update_bank_docs/$', upadate_bank_docs, name='upadate_bank_docs'),


]

aamp/care/forms.py
from django import forms
from .models import CarePointBankDetail, CarePointDocuments



class CareChangePasswordForm(forms.Form):
	password1 = forms.CharField(max_length=50, label="Old Password", widget=forms.PasswordInput())
	password2 = forms.CharField(max_length=50, label="New Password", widget=forms.PasswordInput())

class CareChangePasswordForm(forms.Form):
	password1 = forms.CharField(max_length=50, label="Old Password", widget=forms.PasswordInput())
	password2 = forms.CharField(max_length=50, label="New Password", widget=forms.PasswordInput())

class CarePointBankDetailForm(forms.ModelForm):
	class Meta:
		model = CarePointBankDetail
		fields = [
			'pan_no', 
			'vat_no', 
			'benifit_name',
			'acc_no',
			'neft', 
			'ifsc_code', 
			'acc_type', 
			'bank_name', 
			'branch',
		]
		widgets={
			'pan_no': forms.TextInput(attrs={ 'class': 'form-control', }),
			'vat_no': forms.TextInput(attrs={ 'class': 'form-control', }),
			'benifit_name': forms.TextInput(attrs={ 'class': 'form-control', }),
			'acc_no': forms.TextInput(attrs={ 'class': 'form-control', }),
			'neft': forms.TextInput(attrs={ 'class': 'form-control', }),
			'ifsc_code': forms.TextInput(attrs={ 'class': 'form-control', }),
			'acc_type': forms.Select(attrs={ 'class': 'form-control'}),
			'bank_name': forms.TextInput(attrs={ 'class': 'form-control', }),
			'branch': forms.TextInput(attrs={ 'class': 'form-control', }),
		}

class CarePointDocumentsForm(forms.ModelForm):
	class Meta:
		model = CarePointDocuments
		fields = [
			'id_proof',
			'pan_card',
			'bank_pass',
			]

aamp/care/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from .models import CarePointUserProfile, Taluka, CarePointPincode, CarePointBankDetail, CarePointDocuments, Faqs
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.views.generic.list import ListView
from django.core.mail import send_mail
from django.db.models import Q
# Create your views here.
from .forms import CareChangePasswordForm, CarePointBankDetailForm, CarePointDocumentsForm
from orders.models import Order, UserAddress
from products.models import Category
from .mixins import LoginRequiredMixin
from products.models import Availability
from itertools import chain

import base64
import hmac, base64, struct, time
import hashlib, random, datetime
from django.views.generic.detail import DetailView
import datetime
import time




def mkDateTime(dateString,strFormat="%Y-%m-%d"):
    # Expects "YYYY-MM-DD" string
    # returns a datetime object
    eSeconds = time.mktime(time.strptime(dateString,strFormat))
    return datetime.datetime.fromtimestamp(eSeconds)

def formatDate(dtDateTime,strFormat="%Y-%m-%d"):
    # format a datetime object as YYYY-MM-DD string and return
    return dtDateTime.strftime(strFormat)

def mkFirstOfMonth(dtDateTime):
    #what is the first day of the current month
    #format the year and month + 01 for the current datetime, then form it back
    #into a datetime object
    return mkDateTime(formatDate(dtDateTime,"%Y-%m-01"))

def mkLastOfMonth(dtDateTime):
    dYear = dtDateTime.strftime("%Y")        #get the year
    dMonth = str(int(dtDateTime.strftime("%m"))%12+1)#get next month, watch rollover
    dDay = "1"                               #first day of next month
    nextMonth = mkDateTime("%s-%s-%s"%(dYear,dMonth,dDay))#make a datetime obj for 1st of next month
    delta = datetime.timedelta(seconds=1)    #create a delta of 1 second
    return nextMonth - delta 


def care_user_login(request):
	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				try:
					care_user = CarePointUserProfile.objects.get(user=user)
					if care_user.is_care:	
						login(request, user)
						return HttpResponseRedirect('/care/dashboard/')
					else:
						return HttpResponse("You are not care point user..")
				except:
					return HttpResponse("You are not care point user..")
			else:
				return HttpResponse('User not active.')

		else:
			return HttpResponse("invalid user...")



	return render(request, "care_login.html", {})

@login_required(login_url='/care/')
def change_password(request):
	if request.method == "POST":
		form = CareChangePasswordForm(request.POST)
		if form.is_valid():
			user = User.objects.get(username=request.user.username)
			data = user.check_password(form.cleaned_data['password1'])
			if data:
				user.set_password(form.cleaned_data['password2'])
				user.save()
			else:
				return HttpResponse('Old password did not match...')
	else:
		form = CareChangePasswordForm()

	return render(request, "care/care_change_password.html", {'form': form})


class CareDashboard(LoginRequiredMixin, ListView):
	model = Order
	template_name = "care/index.html"

	def get_context_data(self, *args, **kwargs):
		context = super(CareDashboard, self).get_context_data(*args, **kwargs)
		qs = self.get_queryset()
		order_count = qs.filter(status='delivered').count()
		orders = qs.filter(status='delivered')
		total_commission = 0.00
		for order in orders:
			total_commission += order.get_commission()

		qs1 = qs.filter(status='received')
		qs2 = qs.filter(status='dispatched')
		qs3 = qs.filter(status='intransist')

		query = qs1 | qs2 | qs3

		pending_order_count = query.count()
		total_pending_commission = 0.00
		for order in query.all():
			total_pending_commission += order.get_commission()

		context['total_pending_commission'] = total_pending_commission
		context['pending_order_count'] = pending_order_count
		context['order_count'] = order_count
		context['total_commission'] = total_commission
		return context

	def get_queryset(self, *args, **kwargs):
		qs = super(CareDashboard, self).get_queryset(*args, **kwargs)
		care_point_user = CarePointUserProfile.objects.filter(user=self.request.user)
		taluka = Taluka.objects.filter(user=care_point_user)
		pincodes = CarePointPincode.objects.filter(taluka=taluka)

		qs = self.model.objects.none()

		for pin in pincodes:
			ba = UserAddress.objects.filter(type='billing', postcode=pin)
			for i in ba:
				qs = qs | self.model.objects.filter(billing_address=i)
		return qs


class CareOrderListView(LoginRequiredMixin, ListView):
	model = Order
	template_name = "care/care_orders.html"

	def get_context_data(self, *args, **kwargs):
		context = super(CareOrderListView, self).get_context_data(*args, **kwargs)
		ORDER_STATUS_CHOICES = (
			('all', 'All'),
			('received', 'Received'),
			('dispatched', 'Dispatched'),
			('intransist', 'Intransist'),
			('delivered', 'Delivered'),
			('cancelled', 'Cancelled'),
		)
		context['status'] = ORDER_STATUS_CHOICES
		return context


	def get_queryset(self, *args, **kwargs):
		qs = super(CareOrderListView, self).get_queryset(*args, **kwargs)
		care_point_user = CarePointUserProfile.objects.filter(user=self.request.user)
		taluka = Taluka.objects.filter(user=care_point_user)
		pincodes = CarePointPincode.objects.filter(taluka=taluka)

		qs = self.model.objects.none()

		for pin in pincodes:
			ba = UserAddress.objects.filter(type='billing', postcode=pin)
			for i in ba:
				qs = qs | self.model.objects.filter(billing_address=i)
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(status__icontains=query) |
					Q(payment__icontains=query) |
					Q(billing_address__postcode__icontains=query)|
					Q(order_id__icontains=query) |
					Q(billing_address__full_name__icontains=query)|
					Q(order_id__icontains=query) |
					Q(billing_address__mobile__icontains=query)|
					Q(order_total__icontains=query)
				)
		query2 = self.request.GET.get('status_selector')
		if query2 == "all":
			query2 = None
		if query2:
			qs = qs.filter(
					Q(status__icontains=query2)
				)
		query_from = self.request.GET.get('from')
		query_to = self.request.GET.get('to')
		if query_from and query_to:
			qs = qs.filter(
					Q(timestamp__range=[query_from, query_to])
				)
		return qs

class CareCommission(LoginRequiredMixin, ListView):
	model = Category
	template_name = "care/care_commission.html"


class CareWallet(LoginRequiredMixin, ListView):
	model = Order
	template_name = "care/care_wallet.html"

	def get_context_data(self, *args, **kwargs):
		context = super(CareWallet, self).get_context_data(*args, **kwargs)
		qs = self.get_queryset()
		order_count = qs.filter(status='delivered').count()
		orders = qs.filter(status='delivered')
		total_commission = 0.00
		for order in orders:
			total_commission += order.get_commission()

		from_date = mkFirstOfMonth(datetime.datetime.now())
		to_date = mkLastOfMonth(datetime.datetime.now())

		monthly_order_count = qs.filter(status='delivered', timestamp__range=[from_date, to_date]).count()
		monthly_orders = qs.filter(status='delivered', timestamp__range=[from_date, to_date])
		monthly_order_commission = 0.00
		for order in monthly_orders:
			monthly_order_commission += order.get_commission()

		m_total_commission = 0.00
		for order in monthly_orders:
			m_total_commission += order.get_commission()

		fdate = self.request.GET.get("from")
		tdate = self.request.GET.get("to")
		if fdate and tdate:
			m_total_commission = 0.00
			monthly_orders = qs.filter(status='delivered', timestamp__range=[fdate, tdate])
			for order in monthly_orders:
				m_total_commission += order.get_commission()


		context["m_total_commission"] = m_total_commission
		context["monthly_orders"] = monthly_orders
		context["monthly_order_count"] = monthly_order_count
		context["monthly_commission"] = monthly_order_commission
		context['order_count'] = order_count
		context['total_commission'] = total_commission
		return context

	def get_queryset(self, *args, **kwargs):
		qs = super(CareWallet, self).get_queryset(*args, **kwargs)
		care_point_user = CarePointUserProfile.objects.filter(user=self.request.user)
		taluka = Taluka.objects.filter(user=care_point_user)
		pincodes = CarePointPincode.objects.filter(taluka=taluka)

		qs = self.model.objects.none()

		for pin in pincodes:
			ba = UserAddress.objects.filter(type='billing', postcode=pin)
			for i in ba:
				qs = qs | self.model.objects.filter(billing_address=i)

		return qs




class CareFaqsListView(ListView):
	model = Faqs
	template_name = "care/care_faqs.html"


@login_required(login_url='/care/')
def care_contact(request):
	user_info = CarePointUserProfile.objects.filter(user=request.user)

	for i in user_info:
		if i.email:
			email = i.email
			name = i.get_full_name()
		else:
			email = "None"
			name = i.get_full_name()

	if not request.user.is_anonymous() and not request.user.is_superuser:
		if request.method == "POST":
			# email = 
			question = request.POST.get("que")
			message = "Query form " + name + " is \n" + question + "\n Reply to: " + email
			send_mail('Care Point Query', message, email, ['abhilash.shoffex@gmail.com'], fail_silently=False)
	return render(request, "care/care_contact.html", {})



@login_required(login_url='/care/')
def care_my_account(request):
	context = {}
	user = CarePointUserProfile.objects.get(user=request.user)
	bank_detail = CarePointBankDetail.objects.get(user=user)
	form = CarePointBankDetailForm(instance=bank_detail)

	# docs_img = CarePointDocuments.objects.get_or_create(user=user)

aamp/care/templates/care_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">

    <title>Shoffex Care Point</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style type="text/css">
    .navbar-default .navbar-nav > li > a:hover {
    color: #fff;
    }
    .navbar-default .navbar-brand:hover {
    color: #fff;
    background-color: transparent;
    }
    .navbar{
        margin-bottom: 0px;
    }
    .navbar-default .navbar-brand {
        color: #fff;
    }
    .navbar-default .navbar-nav > li > a {
    color: #FFF;
    }
    .navbar-fixed-top {
    top: 0;
    border-width: 0 0 0px;
    }

    .placeholders {
      margin-bottom: 30px;
      text-align: center;
    }
    .placeholders h4 {
      margin-bottom: 0;
    }
    .placeholder {
      margin-bottom: 20px;
    }
    .placeholder img {
      display: inline-block;
      border-radius: 50%;
    }
    .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover {
    color: #ED7E1F;
    }
    .navbar-default .navbar-nav .open .dropdown-menu > li > a {
    color: #FFFDFD;
    }
    .navbar-default .navbar-nav > li > a {
    color: #FFF;
    }

    /* Wrapper for page content to push down footer */
#wrap {
  min-height: 100%;
  height: auto;
  /* Negative indent footer by its height */
  margin: 0 auto -60px;
  /* Pad bottom by footer height */
  padding: 0 0 60px;
}

.footer {
  position:fixed;
  bottom: 0;
  width: 81%;
  /* Set the fixed height of the footer here */
  height: 50px;
  background-color: #f5f5f5;
}
/* Custom page CSS
-------------------------------------------------- */
/* Not required for template or sticky footer method. */

.container1 {
  width: auto;
  max-width: 680px;
  padding: 0 15px;
}
.container1 .credit1 {
  margin: 20px 0;
}

{% block care_style %}

{% endblock care_style %}
</style>
{% block css %}

{% endblock css %}

</head>

<body style="padding-top: 50px;">
    <!-- care_navbar -->
    {% include 'care_navbar.html' %}
    <!-- end care_navbar -->

    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'care_sidebar.html' %}
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
            {% if messages %}
            <div>
              {% for message in messages %}             
                <div class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %} text-center alert-dismissible'>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                </div>          
              {% endfor %}
           
          </div>
        {% endif %}
            <div>
            <a href="#menu-toggle" style="margin-left:-25px; z-index:999; position: fixed;" class="btn btn-default hidden-lg hidden-sm " id="menu-toggle">Menu</a>
            </div> 
                {% block content %}

                {% endblock content %}
                <br><br><br>
            </div>
            
        </div>
        <!-- /#page-content-wrapper -->

        <div class="footer">
        <div class="container1 text-center">
        <p class="text-muted credit1">&copy; All rights reserved by shoffex.com </p>
        </div>
    </div>
    </div>
    
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/docs.min.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    </script>
    <script>
    $(document).ready(function(){
    {% block jquery %}
    {% endblock jquery %}
});
    </script>

    {% block script %}

    {% endblock script %}
</body>

</html>

aamp/care/templates/care_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<title>Shoffex Carepoint Login</title>

	 <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

	<div class="container" style="background-image: url('paper.gif');">
	<br>
	 {% if messages %}
              {% for message in messages %}             
                <div class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %} text-center alert-dismissible'>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                </div>          
              {% endfor %}
        {% endif %}
	<div class="hidden-xs">
		<br><br><br><br><br>
	</div>
		<div class="row">
			<div class="col-lg-3"></div>
			<div class="col-lg-5 well">
				<h3 align="center" style="font-family: 'Palatino Linotype', 'Book Antiqua', Palatino, serif; padding-bottom: 20px;">Shoffex Care Point Login</h3>
				
				<form action="" method="post">{% csrf_token %}
				<h4>Username</h4> <input type="text" class="form-control" name="username">
				
				<h4>Password</h4> <input type="password" class="form-control" name="password">
				<br>
				<br>
				<button type="submit" class="btn btn-primary btn-block btn-lg">Login</button>
				</form>
				<div align="right">
					<a href="{% url 'care:care_forget_pass' %}">forget password ?</a>
				</div>

			</div>
		</div>
	</div>

	<script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

aamp/care/templates/care_navbar.html
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation" style="background-color: #0d0735;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SHOFFEX CARE POINT</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li style="color:white;">
        <h4><span class="glyphicon glyphicon-shopping-cart"></span></h4>
      </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
          <ul class="dropdown-menu" style="background-color: #3A477D;">
            <li><a href="{% url 'care:change_password' %}">Change Password</a></li>
            <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
            <!-- <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

aamp/care/templates/care_sidebar.html
{% load staticfiles %}
{% load custom_tags %}
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
        {% get_care_user request as care_user %}
            <a href="#">
                <img src="{{ care_user.profile_pic.url }}" style="height: 70px; width: 70px;border-radius: 50px;">
                <span style="color: orange; ">{{ care_user.get_full_name }}</span>
            </a>
        </li>
        <hr>
        <li>
            <a href="{% url 'care:care_dashboard' %}">Dashboard</a>
        </li>
        <li>
            <a href="{% url 'care:care_orders' %}">Orders</a>
        </li>
        <li>
            <a href="{% url 'care:care_commission' %}">Commission</a>
        </li>
        <li>
            <a href="{% url 'care:care_wallet' %}">My Wallet</a>
        </li>
        <li>
            <a href="{% url 'care:care_my_account' %}">My Account</a>
        </li>
        <li>
            <a href="{% url 'care:care_myArea' %}">My Area</a>
        </li>
        <li>
            <a href="{% url 'care:care_faqs' %}">FAQs</a>
        </li>
        <li>
            <a href="{% url 'care:care_contact' %}">Help / Contact Us</a>
        </li>
    </ul>
</div>