aamp/UI/urls.py
from django.conf.urls import include, url
from UI import views
from .views import index, info, poi_list

urlpatterns = [
	url(r'^logo/$', views.index, name="index"),
	url(r'^info/$', info, name="info"),
	url(r'^map/$', views.poi_list, name="map"),
]

aamp/aamp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from useraccount.views import index

from aamp.sitemaps import ProductSitemap, CategorySitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views

from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import (
				AddressSelectFormView, 
				UserAddressCreateView,
				UserShippingAddressCreateView, 
				OrderList, 
				OrderDetail,
				InvoicePDFView,
				UserAddressUpdateView,
				cancel_order,
				admin_orders,
				admin_cancel_order,
				feedback,
                get_feedback,
				)

sitemaps = {
			  'products' : ProductSitemap,
			  'categories': CategorySitemap,
			  'staticPages': StaticViewSitemap
			}

urlpatterns = [
	url(r'^$', index, name="home"),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('useraccount.urls', namespace="account")),
	url(r'^products/', include('products.urls', namespace="products")),
	url(r'^ui/', include('UI.urls', namespace="ui")),

	url('', include('django.contrib.auth.urls', namespace='auth')),

	url(r'^orders/$', OrderList.as_view(), name="orders"),
	url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name="order_detail"),
	url(r'^user-feedback/$', feedback, name="feedback"),
    url(r'^feedback-sent/$', get_feedback, name="feedback_send"),
	url(r'^cancel/(?P<pk>\d+)/$', cancel_order, name="cancel_order"),
	url(r'^adminorders/(?P<pk>\d+)/$', admin_orders, name="admin_orders"),
	url(r'^admincancel/(?P<pk>\d+)/$', admin_cancel_order, name="admin_cancel_order"),

	url(r'^cart/$', CartView.as_view(), name="cart"),
	url(r'^cart/count/$', ItemCountView.as_view(), name="item_count"),
	url(r'^checkout/$', CheckoutView.as_view(), name="checkout"),
	url(r'^checkout/address/$', AddressSelectFormView.as_view(), name="order_address"),
	url(r'^checkout/address/add/$', UserAddressCreateView.as_view(), name="user_address_create"),
	url(r'^checkout/address/change/(?P<pk>\d+)/$', UserAddressUpdateView.as_view(), name="user_address_update"),
	url(r'^checkout/shipping_address/add/$', UserShippingAddressCreateView.as_view(), name="user_shipping_address_create"),
	url(r'^checkout/final/$', CheckoutFinalView.as_view(), name="checkout_final"),
	
	url(r'^invoice/(?P<pk>\d+)/$', InvoicePDFView.as_view(), name='invoice'),

	url(r'^payu/', include('payu.urls', namespace='payu')),

	url(r'^social_accounts/', include('allauth.urls')),

	url(r'^care/', include('care.urls', namespace="care")),

	### SiteMap Indexing ########
	url(r'^sitemap.xml/$', views.index, {'sitemaps': sitemaps}),
	url(r'^sitemap-(?P<section>.+).xml/$', views.sitemap, {'sitemaps': sitemaps}),
	url(r'^robots.txt/', include('robots.urls')),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Shoffex Online Retails India Pvt Ltd'

aamp/products/urls.py
from django.conf.urls import include, url

from .views import ProductDetailView, ProductListView, ProductColorView, category_list, product_rating, availability, Wishlist, add_wishlist

urlpatterns = [

	url(r'^availability/$', availability, name='availability'),
	url(r'^$', ProductListView.as_view(), name="product_list"),
	url(r'^wishlist/$', Wishlist.as_view(), name="wishlist"),
	url(r'^wishlist/(?P<pk>\d+)/$', add_wishlist, name="add_wishlist"),
	url(r'^rating/(?P<pk>\d+)/$', product_rating, name="rating"),
	url(r'^color_view/$', ProductColorView.as_view(), name="color_view"),
    url(r'^(?P<slug>[-\w]+)/$', ProductDetailView.as_view(), name="product_detail"),
    url(r'^category/(?P<slug>[-\w]+)/$', category_list, name="single_category_products"),
]

aamp/useraccount/urls.py
from django.conf.urls import url


from .views import (
		signup, 
		signup_mobile, 
		login_user, 
		user_account, 
		user_settings,
		forget_pass,
		pass_reset,
		replace_pass,
		order_tracking

		)

urlpatterns = [
    url(r'^signup/$', signup, name="signup" ),
    url(r'^order-tracking/$', order_tracking, name="order_tracking" ),
    url(r'^login/$', login_user, name="login_user" ),
    url(r'^mobile/$', signup_mobile, name="signup_mobile" ),
    url(r'^personal/$', user_account, name="user_account" ),
    url(r'^user-settings/$', user_settings, name="user_settings" ),

    url(r'^password/', forget_pass, name="forget_pass"),
    url(r'^reset/', pass_reset, name="password_reset"),
    url(r'^replace/', replace_pass, name="replace_pass"),


]

aamp/orders/models.py
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.html import mark_safe

# Create your models here.
from carts.models import Cart, Shipping
from useraccount.models import SignUp
from django.contrib.auth.models import User
import random 



ADDRESS_TYPE = (
	('billing', 'Billing'),
	('shipping', 'Shipping'),
)


class UserAddress(models.Model):
	full_name = models.CharField(max_length=120)
	user = models.ForeignKey(User)
	type = models.CharField(max_length=120, choices=ADDRESS_TYPE, default='billing', blank=True, null=True)
	street = models.TextField()
	postcode = models.CharField(max_length=6)
	mobile = models.CharField(max_length=10)

	def __unicode__(self):
		return self.street

	def get_address(self):
		return "%s<br/> %s<br/> %s<br/> %s<br/>" %(self.full_name, self.street, self.postcode, self.mobile)


ORDER_STATUS_CHOICES = (
	('received', 'Received'),
	('dispatched', 'Dispatched'),
	('intransist', 'Intransist'),
	('delivered', 'Delivered'),
	('cancelled', 'Cancelled'),
)

class Order(models.Model):
	status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='received')
	order_id = models.CharField(max_length=10, unique=True)
	cart = models.ForeignKey(Cart)
	user = models.ForeignKey(User, null=True)
	billing_address = models.ForeignKey(UserAddress, related_name='billing_address', null=True)
	shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', null=True)
	shipping_total_price = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
	order_total = models.DecimalField(decimal_places=2, max_digits=50)
	payment = models.CharField(max_length=120, blank=True, null=True)
	timestamp = models.DateField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return str(self.order_id)

	class Meta:
		ordering = ['-id']

	def save(self, *args, **kwargs):
		super(Order, self).save(*args, **kwargs)
		order_id = "OD%s" %(random.randrange(1, 100000))
		self.order_id = order_id
		super(Order, self).save()

	def invoice(self):
		url = '<a href="/invoice/%s" target="_blank">Invoice</a>' %(self.pk)
		return mark_safe(url)

	def detail(self):
		url = '<a href="/adminorders/%s">Change Status</a>' %(self.pk)
		return mark_safe(url)

	def get_absolute_url(self):
		return reverse("order_detail", kwargs={"pk": self.pk})

	def mark_completed(self):
		self.status = "received"
		self.save()

	def payment_method(self, method):
		self.payment = method
		self.save()

	def customer_name(self):
		data = ""
		if self.user:
			data = self.billing_address.full_name #user.user.get_full_name()
		else:
			data = "-"
		return str(data)

	def mobile_no(self):
		data = ""
		if self.user:
			data = self.billing_address.mobile #user.user.get_full_name()
		else:
			data = "-"
		return str(data)

	def products(self):
		data = self.cart.cartitem_set.all()
		print data
		li = ""
		for i in data:
			print i.item.product.title
			li = mark_safe("<a href='%s' target='_blank'>%s</a><br/>" %(i.item.get_absolute_url(), i.item.get_title()))
			return li

	def get_pincode(self):
		if self.billing_address is not None:
			return self.billing_address.postcode
		else:
			return None

	def get_commission(self):
		cart = self.cart.cartitem_set.all()
		total_commission = 0.00
		for ca in cart:
			total_commission += ca.quantity * ca.item.product.get_single_product_commission()
		return total_commission



def order_pre_save(sender, instance, *args, **kwargs):
	shipping_total_price = instance.shipping_total_price
	cart_total = instance.cart.total
	order_total = Decimal(shipping_total_price) + Decimal(cart_total)
	instance.order_total = order_total

pre_save.connect(order_pre_save, sender=Order)


class UserComplaint(models.Model):
	order_id = models.IntegerField(blank=True)
	reason = models.TextField(max_length=300, blank=False)
	order_name = models.CharField(max_length=300, blank=True)
	order_price = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
	user = models.CharField(max_length=300, blank=True)

	def __unicode__(self):
		return str(self.order_id)

class AdminComplaint(models.Model):
	admin_order_id = models.IntegerField(blank=True)
	admin_reason = models.TextField(max_length=300, blank=False)
	admin_order_name = models.CharField(max_length=300, blank=True)
	admin_order_price = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
	admin_user = models.CharField(max_length=300, blank=True)

	def __unicode__(self):
		return str(self.admin_user)

aamp/orders/forms.py
from django import forms

from .models import UserAddress
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from useraccount.models import SignUp
from .models import Order



class AddressForm(forms.Form):
	billing_address = forms.ModelChoiceField(
		queryset = UserAddress.objects.filter(type="billing"),
		widget = forms.RadioSelect(attrs={'checked': 'checked', 'class': 'billing', "name": "billing_selected"}),
		empty_label = None,
	)
	shipping_address = forms.ModelChoiceField(
		queryset=UserAddress.objects.filter(type="shipping"),
		widget = forms.RadioSelect(attrs={'checked': 'checked', 'class': 'shipping', "name": "shipping_selected"}),
		empty_label = None,
	)


class UserAddressForm(forms.ModelForm):
	different = forms.BooleanField(label="Same address for shipping", initial=True, required=False)
	class Meta:
		model = UserAddress
		fields = [
			'full_name',
			'street',
			'postcode',
			'type',
			'mobile',			
		]
		widgets={
			'full_name': forms.TextInput(attrs={ 'class': 'form-control', }),
			'street': forms.Textarea(attrs={ 'class': 'form-control', 'rows':1, 'cols':10},),
			'postcode': forms.TextInput(attrs={ 'id': 'postcode', 'class': 'form-control' }),
			'type': forms.Select(attrs={ 'class': 'form-control'}),
			'mobile': forms.TextInput(attrs={ 'id': 'mobile', 'class': 'form-control', }),
		}

	
class OrderForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['status',]
		
		widgets={
				'order_total': forms.TextInput(),
		}

    

aamp/orders/templates/orders/address_select.html
{% extends "base.html" %}

<style type="text/css">
{% block style %}
#id_shipping_address{
	list-style: none;
}
#id_billing_address{
	list-style: none;
}
{% endblock style %}
</style>
<script>
{% block jquery %}
function billing_check(){
	var data = $(".billing:checked").val();
	$("#billing_change_button").attr('href', '/checkout/address/change/'+data)
}
function shipping_check(){
	var data = $(".shipping:checked").val();
	$("#shipping_change_button").attr('href', '/checkout/address/change/'+data)
}
billing_check();
shipping_check();
$(".billing").change(function(){
	var data = $(this).val();
	$("#billing_change_button").attr('href', '/checkout/address/change/'+data)
});
$(".shipping").change(function(){
	var data = $(this).val();
	$("#shipping_change_button").attr('href', '/checkout/address/change/'+data)
});
{% endblock jquery %}
</script>
{% block content %}
<div class="row">
	<form method="POST" action="">{% csrf_token %}
	<div class="text-center"><h2>Select Address</h2></div>
	<div class="col-sm-4 col-sm-offset-2 text-center">
		<div class="panel panel-default">
		  <div class="panel-heading">Shipping Address</div>
		  <div class="panel-body">
		    {{ form.shipping_address }}
		    {{ form.shipping_address.errors }}
		  </div>
		  <div class="panel-footer">
		  	<a href="#" id="shipping_change_button" class="btn btn-warning">Change</a>
		  </div>
		</div>
	</div>
	<div class="col-sm-4 text-center">
		<div class="panel panel-default">
		  <div class="panel-heading">Billing Address</div>
		  <div class="panel-body">
		    {{ form.billing_address }}
		    {{ form.billing_address.errors }}
		  </div>
		  <div class="panel-footer">
		  	<a href="#" id="billing_change_button" class="btn btn-warning">Change</a>
		  </div>
		</div>
	</div>
	
</div>
<div class="text-center">
	{% if data %}
	<input type="submit" class="btn btn-success" value="Continue" />
	{% endif %}
<a class="btn btn-link" href="{% url 'user_address_create' %}">Add new</a>
</div>
</form>
{% endblock %}

aamp/orders/templates/orders/admin_cancel_order.html
{% extends "admin/base.html" %}
{% load staticfiles %}
{% block content %}
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script>
$(document).ready(function(){
		$("#reason_form").hide();
		$("#reason_submit").hide();
		$("#choice").show();	
$("#default").click(function(){
	$("#reason_form").show(1000);
	$("#reason_submit").show(1000);
	$("#button").hide(1000);
	$("#choice").hide(1000);
	$("#choice_submit").hide(1000)
});
$("#list").click(function(){
	$("#choice").show(1000);
	$("#reason_form").hide(1000);
	$("#reason_submit").hide(1000);
	$("#choice_submit").show(1000)
	$("#button").show(1000);
});
$("#choice").click(function(){
	$("#button").hide(1000);
});
		});
</script>

<br>
<h2>Admin Cancellation Form</h2><a href="/adminorders/{{ order.id }}/">Back Order Detail</a>
<hr>
<br>
<form method="post" action="">{% csrf_token %}
<div class="panel panel-default">
  <div class="panel-heading"></div>
  <div class="panel-body">
	<div id="choice">
				<input type="radio" name="reason_choice" value="Product Not Available" required>Product Not Available<br>
				<input type="radio" name="reason_choice" value="PIN code Not Servicable ">PIN code Not Servicable <br>
				<input type="radio" name="reason_choice" value="Delay in Product Arrieval">Delay in Product Arrieval<br>
	</div>
		<div id="default">
			
			<input style="font-size: 10px;margin-left:86px;margin-bottom:-55px;" type="button" id="button" value="Other">
			
		</div>
				
  </div>
  <input style="font-size: 10px;" type="submit" id="choice_submit" value="Submit">
</div>
</form>

<form method="post" action="" id="reason_form">{% csrf_token %}
<div class="panel panel-default">
  <div class="panel-heading"></div>
  <div class="panel-body">
		<div id="reason">
				Reason: <input type="text" name="reason_text" required>
				<input style="font-size: 10px;margin-left:-167px;margin-bottom:-109px;" type="button" id="list" value="List">
		</div>
		<br>
				
  </div>
  <input style="font-size: 10px;" type="submit" id="reason_submit" value="Submit">
</div>
	
</form>
{% endblock %}

aamp/orders/templates/orders/admin_orders.html
{% extends "admin/base.html"%}

{% block jquery %}
$("#b").hide();
{% endblock jquery %}

{% block content %}
<div class="row">
	<div class="col-md-8 col-lg-8">
		<form method="post">{% csrf_token %}
			<table style="width:80%; border: solid 1px #000000; text-align: left; background-color: #d4d4d4;padding: 1px;">
				<tr>
				<td>Order No. <span>{{ order.order_id }}</span> From <span>{{ order.user}}</span></td>
				</tr>
				<tr style="padding-top: 5px; border:none;">
				<th>Order Date</th>
				</tr>
				<tr style="padding-top: 5px; border:none;">
				<td style="background:white;">{{ order.timestamp }}</td>
				</tr>
				<hr>
				<tr>
				<h4 id="b">Update Status: {{ form.status }}</h4>
				</tr>
			</table>
			<div class="row">
				<table style="width:80%; border: solid 1px #000000; text-align: left; background-color: #d4d4d4;padding: 1px;">
					<tr style="padding-top: 5px; border:none;">
					<th>Images</th>
					<th>Product</th>
					<th>Tax Rate</th>
					<th>Unit Price</th>
					<th>Qty</th>
					<th>Total</th>
					</tr>
						{% for i in order.cart.cartitem_set.all %}
					<tr style="padding-top: 5px; border:none;">
					<td style="background:white;">{{ i.item.product.admin_thumbnail}}</td>
					<td style="background:white;">{{ i.item.get_title }}</td>
					<th style="background:white;">-</th>
					<td style="background:white;">{{ i.item.get_price }}</td>
					<td style="background:white;">{{ i.quantity }}</td>
					<td style="background:white;">{{ i.line_item_total }}</td>
					</tr>
					{% endfor %}
					<tr><td><b>Delivery Address</b></td><td><b>Billing Address</b></td></tr>
					<tr>
					<td>
					<address>{{ order.shipping_address.get_address|safe }}</address>
					</td>
					<td>
					<address>{{ order.billing_address.get_address|safe }}</address>
					</td>
					</tr>
					<tr><td></td></tr>
				</table>
			</div>
    		<hr><br><br>
    		<input type="submit" value="Submit" />

		</form>
		<a href="/admin/orders/order/"><input style="margin-left:100px; margin-top: -64px;" type="submit" value="Back" /></a>
	</div>
</div>
{% endblock content %}

aamp/orders/templates/orders/cancel.html
{% extends "base.html" %}

{% block content %}
transaction cancelled

{% endblock content %}

aamp/orders/templates/orders/feedback_submited.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<br>
<div class="row well">
	<div class="col-lg-8" id="thanx" align="center" style="border-right: 1px dashed black;">
		<h3>Thank You for your</h3>
		<h3>Feedback</h3>
		<img src="{% static 'image/thanx.png' %}" class="img-responsive" style="height:200px">
		<br>
		<a href="/"><button class="btn btn-warning">Continue Shopping</button></a>
		<a href="{% url 'account:user_account' %}"><button class="btn btn-info">My Account</button>
		<a href="{% url 'orders' %}"><button class="btn btn-success">My Orders</button></a>
	</div>
	<div class="col-lg-4">
		<h4>Why Give Feedback ?</h4>
		<hr>
		<p>-Your Feedback can help us to improve Shoffex.
		<br>-Dont Hesitate to give Feedback.
		<br>-Feel Free to give Feedback.
		</p>
	</div>
</div>
{% endblock content %}

aamp/orders/templates/orders/order_detail.html
{% extends "base.html" %}


{% block content %}

{% include "orders/order_summary_short.html" with order=object %}

<p><b>Please print for your records</b></p>
{% endblock %}

aamp/orders/templates/orders/order_list.html
{% extends "base.html" %}
{% block jquery %}

{% endblock jquery %}
{% block content %}

<ul class="nav nav-tabs">
	<li class="active"><a data-toggle="pill" href="#orders" style="color: black">Orders</a></li>
	<!-- <li><a data-toggle="pill" href="#open" style="color: black">Open</a></li>
	<li><a data-toggle="pill" href="#cancel" style="color: black">Cancelled Orders</a></li> -->
 </ul>
{% if object_list|length <= 0 %}

<div class="text-center">
	<p class="lead">
		You do not currently have orders.
	</p>
</div>

{% else %}
<br/>
 {% for object in object_list %}
 {% if not object.status == 'cancelled' %}
<div class="tab-content">
	<div id="orders" class="tab-pane fade in active">
		<div class="row" style="background-color: #ccccb3;border: 1px solid black;border-bottom: 0px;">
			<div class="col-lg-2 col-md-2">
				<h5>ORDER PLACED</h5>
				<h5>{{ object.timestamp }}</h5>
			</div>
			<div class="col-lg-2 col-md-2">
				<h5>TOTAL</h5>
				<h5>Rs.{{ object.order_total }}</h5>
			</div>
			<div class="col-lg-3 col-md-3">
				<h5>SHIP TO</h5>
				<h5>{{ object.shipping_address.full_name }}</h5>
			</div>
			<div class="col-lg-1 col-lg-1">
				
			</div>
			<div class="col-lg-3 col-md-3">
				<h5>ORDER #{% if object.order_id %}{{ object.order_id }} {% else %}{{ object.id }}{% endif %}</h5>
				<h5><a href="{% url 'order_detail' object.pk %}">Order Details</a> | <a href="{% url 'invoice' object.id %}" target="_blank">Invoice</a></h5>
				<h5><a href="{% url 'cancel_order' object.pk %}">Cancel Order</a> </h5>
			</div>
			<div class="col-lg-1 col-md-1" style="margin-top: 8px;">
				<span id="show_{{ object.id }}" style="font-size: 12px;" class="label label-success">Show</span>

			</div>
		</div>
		<div id="upper_{{ object.id }}" class="row" style="border: 1px solid black;">
			<h4 style="margin-left: 25px;">Product Information</h4>
			<div class="col-lg-8 col-md-8">
				{% for var in object.cart.items.all %}
				<div>			
					<img src="{{ var.product.get_image_url }}" height="100" width="100">
				</div>
				<div>
					<h6><a href="{{ var.product.get_absolute_url }}">{{ var.product.title }}</a></h6>
					{% if var.product.sale_price %}
					<h6>Rs. {{ var.product.sale_price }}</h6>
					{% else %}
					<h6>Rs. {{ var.product.price }}</h6>
					{% endif %}
				</div>
				{% endfor %}
			</div>	
		
			<div class="col-lg-4 col-md-4">
				<button style="background-color: orange; height: 32px; width:250px"> View Retur/Refund Status</button>
				<a href="{% url 'feedback' %}" style="color:black"><button style="background-color:#ebebe0; height: 32px; width:250px"> Leave Feedback</button></a>
				{% for var in object.cart.items.all %}
				<a href="{% url 'products:rating' var.product.id %}" style="color:black"><button style="background-color:#ebebe0; height: 32px; width:250px"> Write a product review</button></a>
				{% endfor %}
			</div>
		</div>
		<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
		<script type="text/javascript">
			$("#show_{{ object.id }}").click(function(){
				$("#upper_{{ object.id }}").toggle(1000);
			});
			$("#upper_{{ object.id }}").hide();
		</script>
	</div>
</div>
{% else %}
<div class="tab-content">
	<div id="orders" class="tab-pane fade in active">
		<div class="row" style="background-color: #ccccb3;border: 1px solid black;border-bottom: 0px;">
			<div class="col-lg-2 col-md-2">
				<h5>ORDER PLACED</h5>
				<h5>{{ object.timestamp }}</h5>
			</div>
			<div class="col-lg-2 col-md-2">
				<h5>TOTAL</h5>
				<h5>Rs.{{ object.order_total }}</h5>
			</div>
			<div class="col-lg-3 col-md-3">
				<h5>SHIP TO</h5>
				<h5>{{ object.shipping_address.full_name }}</h5>
			</div>
			<div class="col-lg-1 col-lg-1">
				
			</div>
			<div class="col-lg-3 col-md-3">
				<h5>ORDER #{% if object.order_id %}{{ object.order_id }} {% else %}{{ object.id }}{% endif %}</h5>
			</div>
			<div class="col-lg-1 col-md-1" style="margin-top: 8px;">
				<span id="show2_{{ object.id }}" style="font-size: 12px;" class="label label-success">Show</span>

			</div>
		</div>
		<div id="lower_{{ object.id }}" class="row" style="border: 1px solid black;">
			<h4 style="margin-left: 25px;">Product Information</h4>
			<div class="col-lg-8 col-md-8">
				{% for var in object.cart.items.all %}
				<div>			
					<img src="{{ var.product.get_image_url }}" height="100" width="100">
				</div>
				<div>
					<h6><a href="{{ var.product.get_absolute_url }}">{{ var.product.title }}</a></h6>
					{% if var.product.sale_price %}
					<h6>Rs. {{ var.product.sale_price }}</h6>
					{% else %}
					<h6>Rs. {{ var.product.price }}</h6>
					{% endif %}
				</div>
				{% endfor %}
			</div>	
		
			<div class="col-lg-3 col-md-3">
				<span style="font-size: 15px;" class="label label-danger">Order Cancelled</span>
							
				<h5>{{ object.cancel}}</h5>
					
				
					
			</div>
			
		</div>
		<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
		<script>
		$("#lower_{{ object.id }}").hide();
		$(document).ready(function(){
			$("#show2_{{ object.id }}").click(function(){
				$("#lower_{{ object.id }}").toggle(1000);
			});
		});
			// $("#lower_{{ object.id }}").hide();
		</script>
		
	</div>

	

</div>
{% endif %}

{% endfor %}
<br/>
<br/>
{% endif %}
{% endblock content %}

aamp/orders/templates/orders/order_summary_short.html
<p class="lead">Order Summary</p>

<table class="table">
<tr><td>{{ order.cart.cartitem_set.count }} Item(s): <br/><b>{% for i in order.cart.cartitem_set.all %}
{{ i.item.get_title }}<br/> 
{% endfor %}
</b></td></tr>
<tr><td>Cart Subtotal: {{ order.cart.subtotal }}</td></tr>
<tr><td>Tax: {{ order.cart.tax_total }}</td></tr>
<tr><td>Items Total: {{ order.cart.total }}</td></tr>
<tr><td>Shipping: {{ order.shipping_total_price }}</td></tr>
<tr><td>Order Total: {{ order.order_total }}</td></tr>
</table>

<table class="table table-responsive">
	<tr><td>Billing to</td><td>Shipping to</td></tr>
	<tr>
		<td>{{ order.billing_address.get_address|safe }}</td>
		<td>{{ order.shipping_address.get_address|safe }}</td>
	</tr>
</table>

{% if product %}
<hr>
<div class="row">
	<div class="col-lg-1"></div>
	<div class="col-lg-3">
		<a href="{% url 'account:user_account' %}" style="text-decoration: none;"><button class="btn btn-primary btn-lg btn-block">Account</button></a>
	</div>
	<div class="col-lg-1"></div>
	<div class="col-lg-3">
		<a href="{% url 'orders' %}" style="text-decoration: none;"><button class="btn btn-warning btn-lg btn-block">Your Orders</button></a>
	</div>
	<div class="col-lg-1"></div>
	<div class="col-lg-3">
		<a href="/" style="text-decoration: none;"><button class="btn btn-lg btn-success btn-block">Continue Shopping</button></a>
	</div>
</div>
<hr>

	
<h4>User also brought this</h4> 
<div class="row" style="border: 1px solid #e6e6e6;">

	{% for i in product %}
	<div class="col-lg-2" align="center">

		<a href="{{ get_absolute_url }}" class="text-center">
			<div style="overflow: hidden; height: 25px;">
				<h6>{{ i.title }}</h6>
			</div>
		<img src="{{ i.get_image_url }}" style="height:200px; max-width: 100%;"></a>
		<br>
		{% if i.sale_price %}
		<span>Rs. {{ i.sale_price }} <del style="color:red;font-size: 13px;">{{ i.price }}</del></span>
		{% else %}
		<span>Rs. {{ i.price }}</span>
		{% endif %}	
	</div>
	{% endfor %}
</div>
{% endif %}
<br>