aamp/UI/urls.py
from django.conf.urls import include, url
from UI import views
from .views import index, info, poi_list

urlpatterns = [
	url(r'^logo/$', views.index, name="index"),
	url(r'^info/$', info, name="info"),
	url(r'^map/$', views.poi_list, name="map"),
]

aamp/aamp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from useraccount.views import index

from aamp.sitemaps import ProductSitemap, CategorySitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views

from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import (
				AddressSelectFormView, 
				UserAddressCreateView,
				UserShippingAddressCreateView, 
				OrderList, 
				OrderDetail,
				InvoicePDFView,
				UserAddressUpdateView,
				cancel_order,
				admin_orders,
				admin_cancel_order,
				feedback,
                get_feedback,
				)

sitemaps = {
			  'products' : ProductSitemap,
			  'categories': CategorySitemap,
			  'staticPages': StaticViewSitemap
			}

urlpatterns = [
	url(r'^$', index, name="home"),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('useraccount.urls', namespace="account")),
	url(r'^products/', include('products.urls', namespace="products")),
	url(r'^ui/', include('UI.urls', namespace="ui")),

	url('', include('django.contrib.auth.urls', namespace='auth')),

	url(r'^orders/$', OrderList.as_view(), name="orders"),
	url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name="order_detail"),
	url(r'^user-feedback/$', feedback, name="feedback"),
    url(r'^feedback-sent/$', get_feedback, name="feedback_send"),
	url(r'^cancel/(?P<pk>\d+)/$', cancel_order, name="cancel_order"),
	url(r'^adminorders/(?P<pk>\d+)/$', admin_orders, name="admin_orders"),
	url(r'^admincancel/(?P<pk>\d+)/$', admin_cancel_order, name="admin_cancel_order"),

	url(r'^cart/$', CartView.as_view(), name="cart"),
	url(r'^cart/count/$', ItemCountView.as_view(), name="item_count"),
	url(r'^checkout/$', CheckoutView.as_view(), name="checkout"),
	url(r'^checkout/address/$', AddressSelectFormView.as_view(), name="order_address"),
	url(r'^checkout/address/add/$', UserAddressCreateView.as_view(), name="user_address_create"),
	url(r'^checkout/address/change/(?P<pk>\d+)/$', UserAddressUpdateView.as_view(), name="user_address_update"),
	url(r'^checkout/shipping_address/add/$', UserShippingAddressCreateView.as_view(), name="user_shipping_address_create"),
	url(r'^checkout/final/$', CheckoutFinalView.as_view(), name="checkout_final"),
	
	url(r'^invoice/(?P<pk>\d+)/$', InvoicePDFView.as_view(), name='invoice'),

	url(r'^payu/', include('payu.urls', namespace='payu')),

	url(r'^social_accounts/', include('allauth.urls')),

	url(r'^care/', include('care.urls', namespace="care")),

	### SiteMap Indexing ########
	url(r'^sitemap.xml/$', views.index, {'sitemaps': sitemaps}),
	url(r'^sitemap-(?P<section>.+).xml/$', views.sitemap, {'sitemaps': sitemaps}),
	url(r'^robots.txt/', include('robots.urls')),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Shoffex Online Retails India Pvt Ltd'

aamp/care/urls.py
from django.conf.urls import include, url
from .views import (
	care_user_login, 
	CareOrderListView, 
	CareCommission, 
	CareWallet, 
	CareFaqsListView, 
	care_contact, 
	care_my_account, 
	care_myArea, 
	CareDashboard,
	change_password,
	update_user_information,
	care_query_send,
	care_forget_pass,
	update_bank_detail_information,
	upadate_bank_docs,
	CareOrderDetailView,
	)

urlpatterns = [
	url(r'^$', care_user_login, name='care_login'),
	url(r'^faqs/$', CareFaqsListView.as_view(), name='care_faqs'),
	url(r'^forget/', care_forget_pass, name='care_forget_pass'),
	url(r'^dashboard/$', CareDashboard.as_view(), name='care_dashboard'),
	url(r'^orders/$', CareOrderListView.as_view(), name='care_orders'),
	url(r'^orders/(?P<pk>\d+)/$', CareOrderDetailView.as_view(), name='care_order_detail'),
	url(r'^commission/$', CareCommission.as_view(), name='care_commission'),
	url(r'^wallet/$', CareWallet.as_view(), name='care_wallet'),
	url(r'^contact/$', care_contact, name='care_contact'),
	url(r'^account/$', care_my_account, name='care_my_account'),
	url(r'^myarea/$', care_myArea, name='care_myArea'),
	url(r'^change_password/$', change_password, name='change_password'),
	url(r'^update_info/$', update_user_information, name='update_info'),
	url(r'^query_send/$', care_query_send, name='query_send'),
	url(r'^update_bank_info/$', update_bank_detail_information, name='update_bank_info'),
	url(r'^update_bank_docs/$', upadate_bank_docs, name='upadate_bank_docs'),


]

aamp/care/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.



def user_pic_upload_to(instance, filename):
	title = instance.user.username
	slug = slugify(title)
	file_extention = filename.split(".")[1]
	new_filename = "%s-%s.%s" %(slug, instance.id, file_extention)
	return "CarePoint/%s/%s" %(slug, new_filename)

GENDER_TYPE = (
	('male', 'Male'),
	('female', 'Female'),
	)

class CarePointUserProfile(models.Model):
	user = models.OneToOneField(User)
	firstname = models.CharField(max_length=50, blank=True, null=True)
	lastname = models.CharField(max_length=50, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	mobile_no = models.CharField(max_length=10, blank=True, null=True)
	dob = models.DateField(blank=True, null=True)
	gender = models.CharField(max_length=20, choices=GENDER_TYPE, default='male', blank=True, null=True)
	profile_pic = models.ImageField(upload_to=user_pic_upload_to, blank=True, null=True)
	is_care = models.BooleanField(default=False)


	def __unicode__(self):
		return self.firstname

	def get_full_name(self):
		return "%s %s" %(self.firstname, self.lastname)

def care_point_post_saved_receiver(sender, instance, created, *args, **kwargs):
	user = instance
	bank_detail = CarePointBankDetail.objects.get_or_create(user=user)
	bank_docs = CarePointDocuments.objects.get_or_create(user=user)


post_save.connect(care_point_post_saved_receiver, sender=CarePointUserProfile)

ACC_TYPE = (
	('saving', 'Saving'),
	('current', 'Current'),
	)

class CarePointBankDetail(models.Model):
	user = models.OneToOneField(CarePointUserProfile)
	pan_no = models.CharField(max_length=50)
	vat_no = models.CharField(max_length=50)
	benifit_name = models.CharField(max_length=50)
	acc_no = models.CharField(max_length=50)
	neft = models.CharField(max_length=50)
	ifsc_code = models.CharField(max_length=50)
	acc_type = models.CharField(max_length=50, choices=ACC_TYPE, default='saving')
	bank_name = models.CharField(max_length=50)
	branch = models.CharField(max_length=50)

	def __unicode__(self):
		return self.user.firstname

def user_doc_upload_to(instance, filename):
	title = instance.user.firstname
	slug = slugify(title)
	file_extention = filename.split(".")[1]
	new_filename = "%s-%s.%s" %(slug, instance.id, file_extention)
	return "CarePoint/Docs/%s/%s" %(slug, new_filename)

class CarePointDocuments(models.Model):
	user = models.OneToOneField(CarePointUserProfile)
	id_proof = models.FileField(upload_to=user_doc_upload_to, blank=True, null=True)
	pan_card = models.FileField(upload_to=user_doc_upload_to, blank=True, null=True)
	bank_pass = models.FileField(upload_to=user_doc_upload_to, blank=True, null=True)

	def __unicode__(self):
		return self.user.firstname

class Taluka(models.Model):
	user = models.OneToOneField(CarePointUserProfile)
	taluka = models.CharField(max_length=100)

	def __unicode__(self):
		return self.taluka

class CarePointPincode(models.Model):
	taluka = models.ForeignKey(Taluka)
	pincode = models.CharField(max_length=6, unique=True)
	location = models.CharField(max_length=120, blank=True, null=True)

	def __unicode__(self):
		return self.pincode

class Faqs(models.Model):
	question = models.CharField(max_length=200, blank=True, null=True)
	answer = models.TextField(max_length=200, blank=True, null=True)
	pub_date = models.DateTimeField('date_published')

	def __unicode__(self):
		return self.question

	class Meta:
		ordering = ['-pub_date']

aamp/orders/models.py
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.html import mark_safe

# Create your models here.
from carts.models import Cart, Shipping
from useraccount.models import SignUp
from django.contrib.auth.models import User
import random 



ADDRESS_TYPE = (
	('billing', 'Billing'),
	('shipping', 'Shipping'),
)


class UserAddress(models.Model):
	full_name = models.CharField(max_length=120)
	user = models.ForeignKey(User)
	type = models.CharField(max_length=120, choices=ADDRESS_TYPE, default='billing', blank=True, null=True)
	street = models.TextField()
	postcode = models.CharField(max_length=6)
	mobile = models.CharField(max_length=10)

	def __unicode__(self):
		return self.street

	def get_address(self):
		return "%s<br/> %s<br/> %s<br/> %s<br/>" %(self.full_name, self.street, self.postcode, self.mobile)


ORDER_STATUS_CHOICES = (
	('received', 'Received'),
	('dispatched', 'Dispatched'),
	('intransist', 'Intransist'),
	('delivered', 'Delivered'),
	('cancelled', 'Cancelled'),
)

class Order(models.Model):
	status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='received')
	order_id = models.CharField(max_length=10, unique=True)
	cart = models.ForeignKey(Cart)
	user = models.ForeignKey(User, null=True)
	billing_address = models.ForeignKey(UserAddress, related_name='billing_address', null=True)
	shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', null=True)
	shipping_total_price = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
	order_total = models.DecimalField(decimal_places=2, max_digits=50)
	payment = models.CharField(max_length=120, blank=True, null=True)
	timestamp = models.DateField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return str(self.order_id)

	class Meta:
		ordering = ['-id']

	def save(self, *args, **kwargs):
		super(Order, self).save(*args, **kwargs)
		order_id = "OD%s" %(random.randrange(1, 100000))
		self.order_id = order_id
		super(Order, self).save()

	def invoice(self):
		url = '<a href="/invoice/%s" target="_blank">Invoice</a>' %(self.pk)
		return mark_safe(url)

	def detail(self):
		url = '<a href="/adminorders/%s">Change Status</a>' %(self.pk)
		return mark_safe(url)

	def get_absolute_url(self):
		return reverse("order_detail", kwargs={"pk": self.pk})

	def mark_completed(self):
		self.status = "received"
		self.save()

	def payment_method(self, method):
		self.payment = method
		self.save()

	def customer_name(self):
		data = ""
		if self.user:
			data = self.billing_address.full_name #user.user.get_full_name()
		else:
			data = "-"
		return str(data)

	def mobile_no(self):
		data = ""
		if self.user:
			data = self.billing_address.mobile #user.user.get_full_name()
		else:
			data = "-"
		return str(data)

	def products(self):
		data = self.cart.cartitem_set.all()
		print data
		li = ""
		for i in data:
			print i.item.product.title
			li = mark_safe("<a href='%s' target='_blank'>%s</a><br/>" %(i.item.get_absolute_url(), i.item.get_title()))
			return li

	def get_pincode(self):
		if self.billing_address is not None:
			return self.billing_address.postcode
		else:
			return None

	def get_commission(self):
		cart = self.cart.cartitem_set.all()
		total_commission = 0.00
		for ca in cart:
			total_commission += ca.quantity * ca.item.product.get_single_product_commission()
		return total_commission



def order_pre_save(sender, instance, *args, **kwargs):
	shipping_total_price = instance.shipping_total_price
	cart_total = instance.cart.total
	order_total = Decimal(shipping_total_price) + Decimal(cart_total)
	instance.order_total = order_total

pre_save.connect(order_pre_save, sender=Order)


class UserComplaint(models.Model):
	order_id = models.IntegerField(blank=True)
	reason = models.TextField(max_length=300, blank=False)
	order_name = models.CharField(max_length=300, blank=True)
	order_price = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
	user = models.CharField(max_length=300, blank=True)

	def __unicode__(self):
		return str(self.order_id)

class AdminComplaint(models.Model):
	admin_order_id = models.IntegerField(blank=True)
	admin_reason = models.TextField(max_length=300, blank=False)
	admin_order_name = models.CharField(max_length=300, blank=True)
	admin_order_price = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
	admin_user = models.CharField(max_length=300, blank=True)

	def __unicode__(self):
		return str(self.admin_user)

aamp/care/forms.py
from django import forms
from .models import CarePointBankDetail, CarePointDocuments



class CareChangePasswordForm(forms.Form):
	password1 = forms.CharField(max_length=50, label="Old Password", widget=forms.PasswordInput())
	password2 = forms.CharField(max_length=50, label="New Password", widget=forms.PasswordInput())

class CareChangePasswordForm(forms.Form):
	password1 = forms.CharField(max_length=50, label="Old Password", widget=forms.PasswordInput())
	password2 = forms.CharField(max_length=50, label="New Password", widget=forms.PasswordInput())

class CarePointBankDetailForm(forms.ModelForm):
	class Meta:
		model = CarePointBankDetail
		fields = [
			'pan_no', 
			'vat_no', 
			'benifit_name',
			'acc_no',
			'neft', 
			'ifsc_code', 
			'acc_type', 
			'bank_name', 
			'branch',
		]
		widgets={
			'pan_no': forms.TextInput(attrs={ 'class': 'form-control', }),
			'vat_no': forms.TextInput(attrs={ 'class': 'form-control', }),
			'benifit_name': forms.TextInput(attrs={ 'class': 'form-control', }),
			'acc_no': forms.TextInput(attrs={ 'class': 'form-control', }),
			'neft': forms.TextInput(attrs={ 'class': 'form-control', }),
			'ifsc_code': forms.TextInput(attrs={ 'class': 'form-control', }),
			'acc_type': forms.Select(attrs={ 'class': 'form-control'}),
			'bank_name': forms.TextInput(attrs={ 'class': 'form-control', }),
			'branch': forms.TextInput(attrs={ 'class': 'form-control', }),
		}

class CarePointDocumentsForm(forms.ModelForm):
	class Meta:
		model = CarePointDocuments
		fields = [
			'id_proof',
			'pan_card',
			'bank_pass',
			]

aamp/care/templates/care/care_change_password.html
{% extends "care_base.html" %}


{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<form action="" method="post">{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-primary">Change Password</button>
		</form>
	</div>
</div>

{% endblock content %}

aamp/care/templates/care/care_commission.html
{% extends "care_base.html" %}
{% load staticfiles %}
{% block content %}
<h3>Commission</h3>
<hr/>
<div class="row">
	<div class="col-sm-12">
		<table class="table table-responsive"  style="background-color:#A8E3C3;">
			<tr style="background-color:#337ab7;">
				<td style="color:white;"><b>Category</b></td>
				<td style="color:white;"><b>Commission(%)</b></td>
			</tr>
			{% for category in object_list %}
			{% if category.care_commission %}
			<tr>
				<td>{{ category.name }}</td>
				<td>{{ category.care_commission }}%</td>
			</tr>
			{% endif %}
			{% endfor %}
		</table>
	</div>
</div>
<h3>Offers</h3>
<hr/>
<div class="row">
	<div class="col-sm-6 col-xs-12">
		<img src="{% static 'image/offer1.jpg' %}" alt="offer" height="70%" width="70%">
	</div>
	<div class="col-sm-6 col-xs-12">
		<div style="background-color: orange;">
			<marquee><h5>Get <span style="font-size: 30px; color: red;">20% Extra</span> by delivered 10 products in 1 month!!!</h5></marquee>			
		</div>
	</div>
</div>
{% endblock content %}

aamp/care/templates/care/care_contact.html
{% extends "care_base.html" %}
{% load staticfiles %}
{% block content %}

<h3>Contact Us</h3>
<hr/>
<div class="row">
	<div class="col-sm-12"> 
		<form action="{% url 'care:query_send' %}" method="post">
		{% csrf_token %}
			<div class="form-group">
				<label>Question:</label> <textarea class="form-control" type="text" placeholder="Enter Your question" name="que" required="" cols="12" rows="10"></textarea>
			</div>
			<button class="btn btn-success btn-lg">Submit</button>
		</form>
	</div>
</div>
{% endblock content %}

aamp/care/templates/care/care_faqs.html
{% extends "care_base.html" %}
{% load staticfiles %}
{% block content %}
<h3>FAQs</h3>
<hr/>
		
<ol>
{% for que in object_list %}
	
		<li><b>{{ que.question }}</b><br/>{{ que.answer }}</li><br/>
	
	
{% endfor %}
</ol>



{% endblock content %}

aamp/care/templates/care/care_my_account.html
{% extends "care_base.html" %}
{% load staticfiles %}

{% block jquery %}
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#pic').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}
$("#image").change(function(){
	readURL(this);
});

{% endblock jquery %}

{% block content %}

<h3>My Account</h3>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-info">
		  <div class="panel-heading">
		    <h3 class="panel-title">Personal Info</h3>
		  </div>
		  
		  <div class="panel-body">
		  <form action="{% url 'care:update_info' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
		  	<div class="col-lg-2"> 
		    	<img id="pic" name="pic" src="{{ care_user.profile_pic.url }}" style="height:100px; width: 100px;">
		    	<br>
		    	<br>
		    	<!-- <button class="btn btn-default"><span class="glyphicon glyphicon-remove" alt="remove photo"></span> Remove</button>
		    	<br>
		    	<br> -->
		    	<input type="file" id="image" name="image"></input>
		    </div>
		    <div class="col-lg-5">
		    	First Name: <input name="firstname" type="text" class="form-control" value="{{ care_user.firstname }}">
		    	<br>
		    	Email : <input name="email" type="email" class="form-control" value="{{ care_user.email }}">
		    	<br>
		    	Date Of Birth: <input name="dob" type="date" class="form-control" value="{{ care_user.dob|date:"Y-m-d" }}" placeholder="YYYY-MM-DD">
		    </div>
		    <div class="col-lg-5">
		    	Last Name: <input name="lastname" type="text" class="form-control" value="{{ care_user.lastname }}">
		    	<br>
		    	Mobile Number : <input name="mobile_no" type="text" class="form-control" value="{{ care_user.mobile_no }}">
		    	<br>
		    	Gender: &nbsp &nbsp <input type="radio" name="gender" checked=""> Male
		    	&nbsp &nbsp &nbsp		<input type="radio" name="gender"> Female
		    	<br>
		    	<div align="right">
		    		<button class="btn btn-success">Submit</button>
		    	</div>
		    </div>
		    
		    </form>
		  </div>
		</div>
	</div>
</div>


<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Bank Detail</h3>
  </div>
  <div class="panel-body">
  <form action="{% url 'care:update_bank_info' %}" method="post" >{% csrf_token %}
	  <div class="col-lg-6">
	  	Pan Number: {{ form.pan_no }}
	  	<br>
	  	Beneficiary Name:{{ form.benifit_name }}
	  	<br>
	  	RTGS/NEFT: {{ form.neft }}
	  	<br>
	  	Type Of Account: {{ form.acc_type }}
	  	<br>
	  	Branch: {{ form.branch }}
	  </div>
	  <div class="col-lg-6">
	  	VAT/TIN/CST No: {{ form.vat_no }}
	  	<br>
	  	Account Number: {{ form.acc_no }}
	  	<br>
	  	IFSC Code: {{ form.ifsc_code }}
	  	<br>
	  	Bank Name: {{ form.bank_name }}
	  	<br><br>
	  	<div align="right">
			<button class="btn btn-success">Submit</button>
		</div>
	  </div>
		
  </form>  
  </div>
</div>
<div class="panel panel-info">
	  <div class="panel-heading">
	      <h3 class="panel-title">Documents	</h3>
	  </div>
	  <div class="panel-body">
		  <form action="{% url 'care:upadate_bank_docs' %}" method="post" enctype="multipart/form-data" >{% csrf_token %}
			  <div class="col-lg-12">
			  <div>
		
			  	<div style="background-color:#bce8f1; color:#31708f; text-align: center;">ID Proof</div><br>
			  	{{ docs.id_proof }}
			  	<hr>
			  	<div style="background-color:#bce8f1; color:#31708f; text-align: center;">Pan Card</div><br>
			  	{{ docs.pan_card }}
			  	<hr>
			  	<div style="background-color:#bce8f1; color:#31708f; text-align: center;">Bank Passbook</div><br>
			  	{{ docs.bank_pass }}
			  	<hr>
			  	<div align="right">
					<button class="btn btn-success">Submit</button>
				</div>
			  </div>
		  </form>
	  </div>
</div>
<div class="row">
	<div class="col-lg">
		
	</div>
</div>
{% endblock content %}

aamp/care/templates/care/care_orders.html
{% extends "care_base.html" %}
{% load staticfiles %}
{% block css %}
<link href="{% static 'css/datepicker.css' %}" rel="stylesheet">
<style type="text/css">
#datepicker{width:180px; margin: 0 20px 20px 20px;}
#datepicker > span:hover{cursor: pointer;}
</style>
{% endblock css %}

{% block script %}
 <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
 <script>
 	$(function () {
	  $("#datepicker_from").datepicker({ 
	        autoclose: true, 
	        todayHighlight: true,
	        startDate: '-2m',
    		endDate: 'd'
	  });//.datepicker('update', new Date());
	});
	$(function () {
	  $("#datepicker_to").datepicker({ 
	        autoclose: true, 
	        todayHighlight: true,
	        startDate: '2016-01-01',
    		endDate: 'd'
	  });//.datepicker('update', new Date());
	});
 </script>
{% endblock script %}

{% block jquery %}
$("#status_selector").change(function(){
	$("#status_form").submit();
});
{% endblock jquery %}

{% block content %}
<h3>Order List</h3>
<hr/>
<div class="row" style="background-color:#F29552; color:white; border-radius: 4px;">
	<div class="col-sm-4 col-xs-12">
		<form action="" class="navbar-form navbar-right" role="search">
	        <div class="form-group">
	          <input type="text" value="{{ request.GET.q }}" class="form-control" name="q" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
      </form>
	</div>
	<div class="col-sm-5 col-xs-12">
	<form class="navbar-form navbar-left" role="form">
		<div class="form-group">
		<label for="datepicker_from">From:</label>
		<div id="datepicker_from" class="input-group date" data-date-format="yyyy-mm-dd">
		    <input class="input-group-addon" id="from" name="from" style="width:100px;" type="text" placeholder="YYYY-MM-DD" value="{{ request.GET.from }}" readonly />
		</div>
		</div>
		<div class="form-group">
		<label for="datepicker_to">To:</label>
		<div id="datepicker_to" class="input-group date" data-date-format="yyyy-mm-dd">
		    <input class="input-group-addon" id="to" name="to" placeholder="YYYY-MM-DD" style="width:100px;" type="text" value="{{ request.GET.to }}" readonly />
		</div>
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	  </form>
	</div>
	<div class="col-sm-3 col-xs-12">
		<form name="status_form" id="status_form" class="navbar-form navbar-left" role="form">
		<select class="form-control" id="status_selector" name="status_selector">
		{% for i, j in status %}
			{% if i == request.GET.status_selector %}
			<option value="{{ i }}" selected="">{{ j }}</option>		
			{% else %}
			<option value="{{ i }}" >{{ j }}</option>
			{% endif %}
		{% endfor %}
		</select>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div style="overflow-x: auto;padding-top: 10px;">
			<table class="table table-responsive" style="background-color:#A8E3C3;">
				<tr style="background-color:#337ab7;color:white;">
					<td><b>Order ID</b></td>
					<td><b>Customer Name</b></td>
					<td><b>Order Total(Rs)</b></td>
					<td><b>Commission(Rs)</b></td>
					<td><b>Mobile No</b></td>
					<td><b>Payment Type</b></td>
					<td><b>Status</b></td>
					<td><b>Pincode</b></td>
					<td><b>Invoice</b></td>
					<td><b>Commission Details</b></td>
				</tr>
				{% if order_list %}
				{% for order in order_list %}
				<tr>
					<td>{{ order.order_id }}</td>
					<td>{{ order.customer_name }}</td>
					<td>{{ order.order_total }}</td>
					<td>{{ order.get_commission }}</td>
					<td>{{ order.mobile_no }}</td>
					<td>{{ order.payment }}</td>
					<td>{{ order.status }}</td>
					<td>{{ order.get_pincode }}</td>
					<td>{{ order.invoice }}</td>
					<td><a href="{% url 'care:care_order_detail' order.pk %}" target="_blank">details</a></td>
				</tr>
				{% endfor %}
				{% endif %}
			</table>
		</div>
	</div>
</div>
{% endblock content %}

aamp/care/templates/care/care_query_send.html
{% extends "care_base.html" %}

{% block content %}
<div class="row">
<div class="hidden-xs">
<br><br><br> 
</div>
<h3 align="center">Your Query Has Been Send</h3>
</div>

{% endblock content %}